
version: 2

models:
  - name: customer_address_detail
    description: "A starter dbt model"
    columns:
      - name: address_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null