version: "3.9"

services:
  # Airflow setup
  airflow:
    container_name: streamify-airflow
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./core:/opt/airflow
    ports:
      - "8081:8080"
    command: airflow standalone
    networks:
      - data_network

networks:
  data_network:
    driver: bridge
    name: data_network