
version: 2

models:
  - name: dim_customer_detail
    description: "A starter dbt model"
    columns:
      - name: customer_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
  
  - name: dim_datetime
    description: "A starter dbt model"
    columns:
      - name: date_key
        description: "The surrogate key for this table"
        data_tests:
          - unique
          - not_null

      - name: date
        description: "The business key for this table"
        data_tests:
          - unique
          - not_null

  - name: dim_rental_detail
    description: "A starter dbt model"
    columns:
      - name: rental_id
        description: "The business key for this table"
        data_tests:
          - unique
          - not_null

  - name: fact_customer_segment
    description: "A starter dbt model"
    columns:
      - name: rental_id
        description: "The business key for this table"
        data_tests:
          - unique
          - not_null